### ISSUE TITLE
Some suggestions for 1.14

### ISSUE THREAD

**Issue by noobanidus** [lazynessmind/HorseModifiers#5]
- A little more granularity in how much speed each speed upgrade gives would be good, as well as the ability to remove modifiers. Currently my horse is so fast that I blink out of chunk borders...
- The jump upgrade recipe is *ridiculously* expensive. Getting a single rabbit's foot alone, even in modded, can be next to impossible, especially for someone who has a hard time hitting their stupidly tiny hitboxes. Might I suggest pistons instead?

**Comment by lazynessmind** [comment]
Thanks for the suggestions. 

In the next update you will be able add and remove upgrades with the Horse Spy. The recipe was done without much thinking and its really ridiculously expensive and will be changed in the next update.
