### ISSUE TITLE
[1.14.4] Attempted load class Screen DEDICATED_SERVER

### ISSUE THREAD

**Issue by frakier** [lazynessmind/HorseModifiers#7]
forge-1.14.4-28.1.102
horsemodifiers-1.2.1.jar
[And... a alphabet soup list of other mods. If this is not a issue for others running server let me know and I'll turn off the other mods and then turn on only a few at a time to see if I can find any problem mods]

Worked in Singleplayer [using internal server] but crashed on Dedicated Server.

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Horse Modifiers (horsemodifiers) encountered an error during the common_setup event phase
Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER

[crash-2019-12-06_17.34.34-server.txt](https://github.com/lazynessmind/HorseModifiers/files/3934298/crash-2019-12-06_17.34.34-server.txt)

**Comment by Omnimetatron** [comment]
forge-1.14.4-28.1.104
horsemodifiers-1.2.1.jar

Same issue...

https://pastebin.com/TRiA8Z8f

same issue using 1.2.0.jar

https://pastebin.com/TGDVzNFp

**Comment by Wissi** [comment]
Same issue as well.
Using:
forge-1.14.4-28.1.102  &  forge-1.14.4-28.1.104
horsemodifiers-1.2.1.jar

Complete crash log [here](https://gist.github.com/Wissi/a47a33dcbc03d101957467402bfcc6f9).

**Comment by slowiu06** [comment]
Same?
https://hastebin.com/ozumuretay.rb

**Comment by Tander** [comment]
tested with only minecraftforge:28.1.106 and horsemodifiers-1.2.1

https://hatebin.com/ekeauqreae

**Comment by lazynessmind** [comment]
Thanks for the help. The crash happens due to a bad implementation on the server-side of the mod. Unfortunately the GUI is removed for now and a new system to remove and see the status was implemented using the Horse Spy item. The update will be out today, thanks for the patience. (20th December)
