### ISSUE TITLE
Minecraft wont load with version 1.3-1.16.3

### ISSUE THREAD

**Issue by Blugori** [lazynessmind/HorseModifiers#9]
Minecraft crashed just after being launched.

Minecraft ver : 1.16.3
Forge ver : 34.1.33
HorseModifiers ver : 1.3-1.16.3

I'm using a lot of mods, so it might come from incompatibilities
(I dont know why, but I dont have any crash report to provide)

[debug.log](https://github.com/lazyMods/HorseModifiers/files/5466612/debug.log)
[latest.log](https://github.com/lazyMods/HorseModifiers/files/5466613/latest.log)

**Comment by lazynessmind** [comment]
Fixed in daf2e06
Sorry for the inconvenience.
